# Generated by Django 3.2.8 on 2021-10-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menus_owner'),
        ('menus', '0002_photos'),
    ]

    operations = [
    ]
