# Generated by Django 3.2.8 on 2021-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20211019_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='days_selection',
            field=models.BooleanField(default=False),
        ),
    ]
